name: CI/CD counter app

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .

            sudo apt install python3
            sudo pip install pipenv
            sudo pip3 install pipenv
            git init
            git clone https://github.com/cataluniat/django-crud-project 
            cd /django-crud-project
            sudo pipenv --python /usr/bin/python3
            sudo pipenv install
            sudo pipenv shell
            cd app
            python manage.py runserver 
          '
